// <auto-generated />
namespace KPI.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version2201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version2201));
        
        string IMigrationMetadata.Id
        {
            get { return "201910280430352_version22.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
