// <auto-generated />
namespace KPI.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Version106 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version106));
        
        string IMigrationMetadata.Id
        {
            get { return "201912060910123_Version1.0.6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
