// <auto-generated />
namespace KPI.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class vertion4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vertion4));
        
        string IMigrationMetadata.Id
        {
            get { return "201909270925377_vertion4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
