// <auto-generated />
namespace KPI.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version101));
        
        string IMigrationMetadata.Id
        {
            get { return "201911050754441_version1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
